/**
 * Sample React Native App
 *
 * adapted from App.js generated by the following command:
 *
 * react-native init example
 *
 * https://github.com/facebook/react-native
 */

import React, { Component, useState } from 'react';
import { Platform, StyleSheet, Text, View } from 'react-native';
import Calculator from 'react-native-calculator';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#F5FCFF"
  },
  welcome: {
    fontSize: 20,
    textAlign: "center",
    margin: 10
  },
  instructions: {
    textAlign: "center",
    color: "#333333",
    marginBottom: 5
  }
});

const App = async() => {
  const [pingReponse, setPingResponse] = useState("NONE");
  Calculator.pingCallback("hello", 1, (responseString)=>{
    setPingResponse(responseString);
  })
  return (
    <View style={styles.container}>
      <Text style={styles.welcome}>Response from Native: {pingReponse}</Text>
    </View>
  );
}
export default App;
